const variants={A:'独立菜单（推荐）',B:'精品班工作台',C:'左右分栏管理'};
const state={surface:'admin',section:'users',modal:null,login:false,denied:false,player:false,userCount:128,videoCount:24,editingCourseSort:null};
const users=[['陈晨','138****2608','市场一部','启用','2026-09-16 10:20','今天 09:20','李管理员'],['王楠','wangnan@***','内容中心','启用','2026-09-15 14:32','昨天 16:42','李管理员'],['赵欣','186****9211','渠道合作部','启用','2026-09-14 11:08','9月14日','周管理员'],['林嘉','linjia@***','外部合作方','停用','2026-09-12 09:15','9月12日','李管理员'],['徐乐','159****4432','客户成功部','停用','2026-08-29 17:40','8月29日','周管理员']];
const premiumCourses=[['超越自我·成长课程','自信力','MP4','1.2MB','31秒','正常','2026-09-16 11:02','JP-20489',10],['孩子玩手机致父亲损失钱财','亲子沟通','MP4','10.2MB','9分17秒','正常','2026-09-15 18:40','JP-20490',20],['亲子沟通：损失钱财之后','亲子沟通','MP3','8.5MB','9分17秒','正常','2026-09-15 18:39','JP-20491',30],['杨学超：感恩无限','成长课程','MP3','8.6MB','9分20秒','原资源下架','2026-09-12 13:18','JP-20492',40]];
const candidates=[['家庭关系与边界','家庭教育','MP4','1.46GB','21分03秒',false],['青春期沟通的三个误区','亲子沟通','MP4','868MB','18分40秒',false],['如何建立家庭规则','家庭教育','MP4','560MB','12分05秒',false],['超越自我·成长课程','自信力','MP4','1.2MB','31秒',true],['孩子玩手机致父亲损失钱财','亲子沟通','MP4','10.2MB','9分17秒',true]];

function currentVariant(){const key=new URLSearchParams(location.search).get('variant')?.toUpperCase();return variants[key]?key:'A'}
function shell(content,compact=false){return `<header class="topbar"><div class="brand"><span class="brand-mark">▶</span> 内容管理平台 <span class="prototype-tag">PROTOTYPE</span></div><div class="user"><span>帮助</span><span class="avatar">李</span><span>李管理员</span></div></header><div class="layout"><aside class="sidebar"><small>工作台</small><div class="menu">⌂ 首页</div><small>内容中心</small><div class="menu">▣ 视频库</div><div class="menu">▤ 标签管理</div><small>精品班管理</small><div class="menu ${state.section==='users'?'active':''}" onclick="state.section='users';render()">♙ 精品班用户</div><div class="menu ${state.section==='videos'?'active':''}" onclick="state.section='videos';render()">▶ 精品班课程</div><small>系统</small><div class="menu">⚙ 系统设置</div></aside><main class="main ${compact?'compact':''}">${content}</main></div>`}
function pageHead(){const isUsers=state.section==='users';return `<div class="pagehead"><div><div class="minor">精品班管理 / ${isUsers?'精品班用户':'精品班课程'}</div><h1>${isUsers?'精品班用户':'精品班课程'}</h1><div class="sub">${isUsers?'管理可登录观看精品班课程的用户，停启用仅影响精品班访问。':'从现有视频库中选择对精品班用户开放的内容。'}</div></div><button class="btn primary" onclick="openModal('${isUsers?'addUser':'selectVideo'}')">＋ ${isUsers?'新增精品班用户':'从视频库选择'}</button></div>`}
function usersPage(){const rows=users.map((u,i)=>`<tr><td><div class="person"><span class="avatar">${u[0][0]}</span><div><b>${u[0]}</b><div class="minor">${u[1]}</div></div></div></td><td><span class="badge ${u[3]==='启用'?'green':'gray'}">${u[3]}</span></td><td>${u[4]}</td><td>${u[6]}</td><td><button class="btn ghost ${u[3]==='启用'?'danger':''}" onclick="toggleUser(${i})">${u[3]==='启用'?'停用':'启用'}</button></td></tr>`).join('');return `${pageHead()}<section class="card"><div class="toolbar"><input class="input" placeholder="姓名 / 手机号 / 账号"/><select class="select"><option>全部状态</option><option>启用</option><option>停用</option></select><button class="btn primary">查询</button><button class="btn">重置</button></div><div class="table-wrap"><table><thead><tr><th>用户</th><th>状态</th><th>加入时间</th><th>操作人</th><th>操作</th></tr></thead><tbody>${rows}</tbody></table></div></section>`}
function videosPage(){const rows=premiumCourses.map((v,i)=>`<tr><td>${state.editingCourseSort===v[7]?`<input class="sort-input" type="number" min="0" max="9999" value="${v[8]}" aria-label="修改${v[0]}的排序值" onkeydown="handleSortKey(event,'${v[7]}',this)" onblur="saveCourseSort('${v[7]}',this)"/>`:`<button class="sort-value" title="点击修改排序" onclick="startEditSort('${v[7]}')">${v[8]}</button>`}</td><td><div class="person"><span class="video-thumb">${v[2]==='MP3'?'♫':'▶'}</span><div><b>${v[0]}</b><div class="minor">课程ID：${v[7]}</div></div></div></td><td>${v[2]}</td><td>${v[3]}</td><td>${v[4]}</td><td><span class="badge ${v[5]==='正常'?'green':'red'}">${v[5]}</span></td><td>${v[6]}</td><td><button class="btn ghost" onclick="state.player=true;render()">查看</button><button class="btn ghost danger" onclick="confirmRemove(${i})">移除</button></td></tr>`).join('');return `${pageHead()}<div class="note" style="margin-bottom:16px">点击蓝色排序值可原位修改，回车或点击空白处保存；数值越小越靠前，用户端同步按此顺序展示。新选课程默认排在末尾。</div><section class="card"><div class="toolbar"><input class="input" placeholder="请输入视频名称"/><select class="select"><option>全部类型</option><option>MP4</option><option>MP3</option></select><button class="btn primary">查询</button><button class="btn">重置</button><span style="flex:1"></span><span class="sub">已选择 ${state.videoCount} 个资源</span></div><div class="table-wrap"><table><thead><tr><th>排序</th><th>课程</th><th>类型</th><th>文件大小</th><th>时长</th><th>原资源状态</th><th>加入时间</th><th>操作</th></tr></thead><tbody>${rows}</tbody></table></div></section>`}
function variantA(){return shell(state.section==='users'?usersPage():videosPage())}
function variantB(){const cards=`<section class="stats"><div class="card stat"><div class="label">精品班用户</div><div class="num">${state.userCount}</div><button class="btn ghost" onclick="state.section='users';render()">管理用户 →</button></div><div class="card stat"><div class="label">精品班课程</div><div class="num">${state.videoCount}</div><button class="btn ghost" onclick="state.section='videos';render()">管理课程 →</button></div><div class="card stat"><div class="label">今日播放</div><div class="num">86</div></div><div class="card stat"><div class="label">异常资源</div><div class="num" style="color:var(--red)">1</div></div></section>`;const content=`<div class="pagehead"><div><div class="minor">精品班管理</div><h1>精品班工作台</h1><div class="sub">人员名单和开放课程分开维护，统一查看运行状态。</div></div><div><button class="btn" onclick="openModal('addUser')">＋ 新增用户</button> <button class="btn primary" onclick="openModal('selectVideo')">＋ 选择课程</button></div></div>${cards}<div class="two-column"><section class="card"><div class="panel-head"><h2>最近加入的精品班用户</h2><button class="btn ghost" onclick="state.section='users';render()">查看全部</button></div>${users.slice(0,4).map(u=>`<div class="list-row"><div class="person"><span class="avatar">${u[0][0]}</span><div><b>${u[0]}</b><div class="minor">加入时间：${u[4]}</div></div></div><span class="badge ${u[3]==='启用'?'green':'gray'}">${u[3]}</span></div>`).join('')}</section><section class="card"><div class="panel-head"><h2>最近选择的精品班课程</h2><button class="btn ghost" onclick="state.section='videos';render()">查看全部</button></div>${premiumCourses.slice(0,4).map(v=>`<div class="list-row"><div><b>${v[0]}</b><div class="minor">${v[2]} · ${v[4]}</div></div><span class="badge ${v[5]==='正常'?'green':'red'}">${v[5]}</span></div>`).join('')}</section></div>`;return shell(content)}
function variantC(){const isUsers=state.section==='users';const left=`<section class="split-nav"><div class="split-item ${isUsers?'active':''}" onclick="state.section='users';render()"><b>精品班用户</b><span>${state.userCount} 人</span><small>管理谁可以访问</small></div><div class="split-item ${!isUsers?'active':''}" onclick="state.section='videos';render()"><b>精品班课程</b><span>${state.videoCount} 个</span><small>管理可以看什么</small></div><div class="formula"><b>开放规则</b><p>启用用户 × 已选视频</p><small>两个条件同时满足才能播放</small></div></section>`;return shell(`<div class="pagehead"><div><div class="minor">精品班管理</div><h1>访问范围</h1><div class="sub">把“人”和“内容”作为两个独立清单维护。</div></div></div><div class="split-layout">${left}<section class="split-content">${isUsers?usersPage():videosPage()}</section></div>`,true)}
function addUserModal(){return `<div class="modal-layer" onclick="if(event.target===this)closeModal()"><section class="modal-card"><div class="modal-head"><div><h2>新增精品班用户</h2><div class="sub">从现有系统用户中选择，新增后默认启用。</div></div><button class="x" onclick="closeModal()">×</button></div><div class="field"><label>搜索用户</label><input value="陈" placeholder="输入姓名、手机号或账号"/></div><div class="search-results"><label class="check-row"><input type="checkbox" checked/><span class="avatar">陈</span><span><b>陈小雨</b><span class="minor" style="display:block">137****0831</span></span><span style="margin-left:auto" class="badge green">账号正常</span></label><label class="check-row"><input type="checkbox"/><span class="avatar">陈</span><span><b>陈路</b><span class="minor" style="display:block">chenlu@***</span></span><span style="margin-left:auto" class="badge green">账号正常</span></label></div><div class="note" style="margin-top:16px">停用精品班用户只影响精品班课程，不会停用系统账号。</div><div class="modal-actions"><button class="btn" onclick="closeModal()">取消</button><button class="btn primary" onclick="saveUser()">确认新增（1人）</button></div></section></div>`}
function selectVideoModal(){return `<div class="modal-layer" onclick="if(event.target===this)closeModal()"><section class="modal-card wide"><div class="modal-head"><div><h2>从视频库选择</h2><div class="sub">这里只建立引用，不会复制或修改原视频。</div></div><button class="x" onclick="closeModal()">×</button></div><div class="toolbar" style="padding:0 0 14px"><input class="input" placeholder="视频名称"/><select class="select"><option>全部类型</option><option>MP4</option><option>MP3</option></select><button class="btn primary">查询</button></div><div class="candidate-list">${candidates.map((v,i)=>`<label class="candidate ${v[5]?'disabled':''}"><input type="checkbox" ${i<2&&!v[5]?'checked':''} ${v[5]?'disabled':''}/><span class="video-thumb">${v[2]==='MP3'?'♫':'▶'}</span><span style="flex:1"><b>${v[0]}</b><span class="minor" style="display:block">${v[2]} · ${v[3]} · ${v[4]}</span></span>${v[5]?'<span class="badge gray">已添加</span>':'<span class="badge green">可选择</span>'}</label>`).join('')}</div><div class="modal-actions"><span class="sub" style="margin-right:auto">已选择 2 个视频</span><button class="btn" onclick="closeModal()">取消</button><button class="btn primary" onclick="saveVideos()">确认添加</button></div></section></div>`}
function confirmModal(){const {type,index}=state.modal;const isUser=type==='confirmUser';const target=isUser?users[index]:premiumCourses[index];const disabling=isUser&&target[3]==='启用';return `<div class="modal-layer"><section class="confirm-card"><div class="confirm-icon">${isUser?'♙':'▶'}</div><h2>${isUser?(disabling?'确认停用精品班用户？':'确认启用精品班用户？'):'从精品班课程中移除？'}</h2><p class="sub">${isUser?(disabling?`停用后，${target[0]} 将无法查看和播放精品班课程，但系统账号不受影响。`:`启用后，${target[0]} 将可以访问全部精品班课程。`):`“${target[0]}”将不再对精品班用户开放，但不会删除视频库原资源。`}</p><div class="modal-actions"><button class="btn" onclick="closeModal()">取消</button><button class="btn ${disabling||!isUser?'danger':'primary'}" onclick="doConfirm()">确认${isUser?(disabling?'停用':'启用'):'移除'}</button></div></section></div>`}
function modal(){if(!state.modal)return'';if(state.modal==='addUser')return addUserModal();if(state.modal==='selectVideo')return selectVideoModal();return confirmModal()}
function portal(){if(state.login)return `<div class="login-shell"><section class="login-art"><div class="brand"><span class="brand-mark" style="background:white;color:var(--blue)">精</span> 精品班学习空间</div><h1>看见成长<br/>也陪伴成长</h1><p>仅面向已启用的精品班用户开放。</p></section><section class="login-form"><h2>登录精品班</h2><p class="sub">登录后系统将验证精品班用户状态</p><div class="field"><label>账号 / 手机号</label><input value="demo_user"/></div><div class="field"><label>密码</label><input type="password" value="12345678"/></div><button class="btn primary" onclick="state.login=false;render()">登录</button><button class="btn" style="border:0" onclick="state.login=false;state.denied=true;render()">模拟停用用户</button></section></div>`;if(state.denied)return `<div class="denied"><div class="denied-card"><div class="denied-icon">🔒</div><h2>当前账号未开通精品班课程</h2><p class="sub">该账号不是精品班用户或已被停用，请联系业务管理员。</p><button class="btn" onclick="state.denied=false;state.login=true;render()">切换账号</button><button class="btn primary" onclick="state.surface='admin';state.denied=false;render()">返回后台演示</button></div></div>`;return `<div class="portal"><header class="portal-head"><div class="brand"><span class="brand-mark">精</span> 精品班学习空间</div><div class="user"><span class="badge green">精品班用户 · 已启用</span><span class="avatar">陈</span><span>陈晨</span></div></header><main class="portal-main"><section class="hero"><div><h1>欢迎回来，陈晨</h1><div style="opacity:.8">精选 ${state.videoCount} 门课程，陪你持续学习</div></div><input placeholder="搜索精品班课程"/></section><div class="pagehead"><div><h1 style="font-size:20px">精品班课程</h1><div class="sub">内容均从平台视频库精选</div></div></div>${mediaCards()}</main></div>`}
function mediaCards(){return `<div class="resource-grid">${premiumCourses.filter(v=>v[5]==='正常').map((v,i)=>`<article class="card media-card"><div class="cover c${(i%3)+1}">${v[2]==='MP3'?'♫':'▶'}<span class="duration">${v[4]}</span></div><div class="media-body"><div class="media-title">${v[0]}</div><div class="minor">${v[2]} · ${v[4]}</div><button class="btn ghost" style="margin-top:8px" onclick="state.player=true;render()">立即观看</button></div></article>`).join('')}</div>`}
function player(){if(!state.player)return'';return `<div class="modal-layer" onclick="if(event.target===this){state.player=false;render()}"><section class="player-modal"><div class="modal-head"><div><h2>超越自我·成长课程</h2><div class="minor">播放前校验：精品班用户已启用 + 视频已加入精品班课程</div></div><button class="x" onclick="state.player=false;render()">×</button></div><div class="player"><div><div class="play">▶</div><b>视频播放演示</b><div class="minor" style="color:#aeb7ca">播放地址为短时效授权凭证</div></div></div></section></div>`}
function switcher(){const key=currentVariant();return `<div class="prototype-switcher"><button onclick="cycle(-1)">←</button><div class="switch-label">${key} — ${variants[key]}</div><button onclick="cycle(1)">→</button></div><div class="view-mode"><button class="${state.surface==='admin'?'active':''}" onclick="state.surface='admin';render()">管理端</button><button class="${state.surface==='portal'?'active':''}" onclick="state.surface='portal';state.login=true;render()">用户端</button></div>`}
function render(){const content=state.surface==='portal'?portal():currentVariant()==='A'?variantA():currentVariant()==='B'?variantB():variantC();document.querySelector('#app').innerHTML=content+modal()+player()+switcher()}
function cycle(delta){const keys=Object.keys(variants);const next=keys[(keys.indexOf(currentVariant())+delta+keys.length)%keys.length];const url=new URL(location.href);url.searchParams.set('variant',next);history.replaceState({},'',url);render()}
function openModal(type){state.modal=type;render()}function closeModal(){state.modal=null;render()}function toggleUser(index){state.modal={type:'confirmUser',index};render()}function confirmRemove(index){state.modal={type:'confirmVideo',index};render()}
function doConfirm(){const{type,index}=state.modal;if(type==='confirmUser'){const enabling=users[index][3]==='停用';users[index][3]=enabling?'启用':'停用';state.modal=null;render();toast(enabling?'精品班用户已启用':'精品班用户已停用，系统账号不受影响')}else{premiumCourses.splice(index,1);state.videoCount--;state.modal=null;render();toast('已从精品班课程移除，视频库原资源未删除')}}
function saveUser(){users.unshift(['陈小雨','137****0831','市场二部','启用','刚刚','—','李管理员']);state.userCount++;state.modal=null;render();toast('陈小雨已加入精品班用户并启用')}
function saveVideos(){const nextSort=Math.max(...premiumCourses.map(v=>v[8]),0)+10;premiumCourses.push(['家庭关系与边界','家庭教育','MP4','1.46GB','21分03秒','正常','刚刚','JP-20501',nextSort],['青春期沟通的三个误区','亲子沟通','MP4','868MB','18分40秒','正常','刚刚','JP-20502',nextSort+10]);state.videoCount+=2;state.modal=null;render();toast('已添加 2 个精品班课程，并排在列表末尾')}
function startEditSort(courseId){state.editingCourseSort=courseId;render();requestAnimationFrame(()=>{const input=document.querySelector('.sort-input');if(input){input.focus();input.select()}})}
function saveCourseSort(courseId,input){if(state.editingCourseSort!==courseId)return;const value=Number(input.value);const course=premiumCourses.find(v=>v[7]===courseId);if(!Number.isInteger(value)||value<0||value>9999){state.editingCourseSort=null;render();toast('排序值请输入 0—9999 的整数');return}course[8]=value;premiumCourses.sort((a,b)=>a[8]-b[8]);state.editingCourseSort=null;render();toast('排序已保存，用户端展示顺序已同步')}
function handleSortKey(event,courseId,input){if(event.key==='Enter'){event.preventDefault();input.blur()}if(event.key==='Escape'){event.preventDefault();state.editingCourseSort=null;render()}}
function toast(message){const old=document.querySelector('.toast');if(old)old.remove();const el=document.createElement('div');el.className='toast';el.textContent=message;document.body.appendChild(el);setTimeout(()=>el.remove(),2600)}
document.addEventListener('keydown',e=>{const tag=document.activeElement?.tagName;if(['INPUT','TEXTAREA','SELECT'].includes(tag)||document.activeElement?.isContentEditable)return;if(e.key==='ArrowLeft')cycle(-1);if(e.key==='ArrowRight')cycle(1)});render();
